[workspace]
resolver = "2"
members = [
    "dftd4", "dftd4-src"
]

[workspace.package]
edition = "2021"
version = "0.2.0"
description = "dftd4 FFI bindings, wrappers and build-from-source"
repository = "https://github.com/RESTGroup/dftd4-rs"
keywords = ["ffi", "chemistry"]
categories = ["science"]
license = "LGPL-3.0"

[workspace.dependencies]
