//! Base types and imports for FFI.
//!
//! This file is generated automatically.

#![allow(non_camel_case_types)]

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd4_error {
    _unused: [u8; 0],
}
#[doc = " Error handle class"]
pub type dftd4_error = *mut _dftd4_error;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd4_structure {
    _unused: [u8; 0],
}
#[doc = " Molecular structure data class"]
pub type dftd4_structure = *mut _dftd4_structure;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd4_model {
    _unused: [u8; 0],
}
#[doc = " Dispersion model class"]
pub type dftd4_model = *mut _dftd4_model;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _dftd4_param {
    _unused: [u8; 0],
}
#[doc = " Damping parameter class"]
pub type dftd4_param = *mut _dftd4_param;
