[package]
name = "dftd4"
description = "FFI bindings and wrappers of dftd4"
readme = "readme.md"

version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
derive_builder = { version = "0.20" }
duplicate = { version = "2.0" }

[dev-dependencies]
rstest = { version = "0.25" }
approx = { version = "0.5" }

[features]
d4s = []

[[example]]
name = "energy_r2scan"
doc-scrape-examples = true

[[example]]
name = "gradient_b97m"
doc-scrape-examples = true
