name: test-dftd4

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-static-loading:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - name: run tests directly
        run: |
          sudo apt install libblas-dev liblapack-dev -y
          cd dftd4
          conda install dftd4-python -c conda-forge
          ls /usr/share/miniconda/lib
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/lib
          export DFTD4_DEV=1
          cargo test --no-default-features --features="api-v4_0" -- --nocapture
          cargo test --no-default-features --features="api-v4_0" --examples -- --nocapture

  test-dynamic-loading:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - name: run tests directly
        run: |
          sudo apt install libblas-dev liblapack-dev -y
          cd dftd4
          conda install dftd4-python -c conda-forge
          ls /usr/share/miniconda/lib
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/lib
          cargo test -- --nocapture
          cargo test --examples -- --nocapture
